// let currentIndex = 0;
// const items = document.querySelectorAll('carousel-item');
// const totalItems = items.length
// const carousel = document.querySelector('.carousel');
// const prevButton = document.querySelector('.carousel-prev');
// const nextButton = document.querySelector('.carousel-next');
// document.querySelector('.carousel-next').addEventListener('click', () => {
//   items[currentIndex].classList.remove('active');
//   currentIndex = (currentIndex + 1) % totalItems;
//   items[currentIndex].classList.add('active');
// });

// document.querySelector('.carousel-prev').addEventListener('click', () => {
//   items[currentIndex].classList.remove('active');
//   currentIndex = (currentIndex - 1 + totalItems) % totalItems;
//   items[currentIndex].classList.add('active');
// });
// nextButton.addEventListener('click', () => {
//     carousel.scrollBy({ left: carousel.offsetWidth, behavior: 'smooth' });
// });

// prevButton.addEventListener('click', () => {
//     carousel.scrollBy({ left: -carousel.offsetWidth, behavior: 'smooth' });
// });
